# Site settings
title: Socialgorithm
email: hello@socialgorithm.org
description: We organise hackathons, workshops and coding challenges. Get in touch if you want to host an event!

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://socialgorithm.org" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-119875762-1"
#disqus_account: socialgorithm

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: github
    url: https://github.com/socialgorithm
  - title: twitter
    url: https://twitter.com/Socialgorithm_
  - title: slack
    url: https://socialgorithm-slack.herokuapp.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins_dir: [jekyll-paginate, jekyll-feed, jemoji]
# Build settings

exclude: [ node_modules, .sass-cache, .git, less, _sass ]
